print("##############################")
print("#                            #")
print("# Muhammad Putra Azky Alfani #")
print("#       2310817210026        #")
print("#                            #")
print("##############################")